In [1]:
# loading library
import cv2
import numpy as np

In [62]:
np.set_printoptions(threshold=np.inf)

In [65]:
img = cv2.imread('30_30_car.jpg',cv2.IMREAD_GRAYSCALE)

In [87]:
# Specify the kernel size.
# The greater the size, the more the motion.
kernel_size = 2

In [88]:
# Create the vertical kernel.
kernel_v = np.zeros((kernel_size, kernel_size))
  
# Create a copy of the same for creating the horizontal kernel.
kernel_h = np.copy(kernel_v)

In [89]:
# Fill the middle row with ones.
kernel_v[:, int((kernel_size - 1)/2)] = 1
kernel_h[int((kernel_size - 1)/2), :] = 1

In [90]:
kernel_h

array([[1., 1.],
       [0., 0.]])

In [91]:
my_arr = [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]

In [92]:
x =  np.diagflat([1/5,1/5,1/5,1/5,1/5])
print(x)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [93]:
# gaussian kernel 
kernel_g = np.ones((5,5),np.float32)/25

In [94]:
# Normalize.
kernel_v /= kernel_size
kernel_h /= kernel_size

In [95]:
# Apply the vertical kernel.
vertical_mb = cv2.filter2D(img, -1, kernel_v)

In [96]:
# Apply the horizontal kernel.
horizonal_mb = cv2.filter2D(img, -1, kernel_h)

In [97]:
# Apply the gaussian kernel.
x_mb = cv2.filter2D(img, -1, x)

In [85]:
cv2.imshow("img01", x_mb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [98]:
# Save the outputs.
cv2.imwrite('car_Gaussian.jpg', vertical_mb)
# cv2.imwrite('car_horizontal.jpg', horizonal_mb)

True

In [86]:
x_mb

array([[ 21,  19,  21,  21,  28,  34,  28,  23,  25,  25,  10,  29,  30,
         37,  43,  51,  54,  48,  44,  32,  28,  19,  31,  32,  21,  19,
         29,  32,  21,  20,  31,  30,  32,  36,  56,  34,  42,  46,  65,
         42,  35,  34,  35,  27,  25,  30,  31,  23,  31,  34],
       [ 18,  19,  21,  23,  25,  28,  32,  28,  21,  25,  27,  21,  34,
         38,  45,  52,  50,  49,  40,  40,  23,  19,  14,  26,  27,  22,
         13,  13,  15,  16,  16,  30,  51,  35,  41,  55,  29,  34,  50,
         38,  32,  29,  28,  30,  22,  22,  38,  41,  38,  33],
       [ 17,  15,  18,  21,  24,  21,  26,  32,  23,  19,  21,  31,  28,
         37,  45,  51,  57,  42,  40,  35,  32,  16,  24,  24,  23,  25,
         20,  10,  22,  35,  16,  61,  54,  93,  74,  83,  97,  34,  46,
         48,  40,  26,  35,  21,  34,  27,  42,  39,  69,  45],
       [ 19,  19,  16,  18,  22,  23,  24,  30,  26,  30,  19,  26,  35,
         37,  63,  42,  42,  53,  35,  32,  30,  32,  18,  22,  23,  22,
     

In [81]:
img

array([[ 23,  12,   7,  15,  31,  96,  25,  13,  29,  33,   4,  19,  20,
         50,  51,  50,  52,  49,  53,   7,  11,   9,  11,  11,  11,  11,
         11,  12,  10,   9,  15,   6,  10,  21,   9,  16,  19,  55,  56,
         25,  26,  32,  33,  36,  16,   8,  21,  49,  10,  14],
       [ 22,  25,  26,  26,  19,  49,  27,  39,  32,  21,  39,  11,  17,
         48,  48,  50,  50,  60,  55,  22,   9,  15,   9,  14,  15,  13,
         14,  15,  13,  14,  18,  30,  25,  20,  20,  26,  14,  60,  59,
         27,  37,  35,  27,  41,  28,   0,  14,  53,  20,  21],
       [ 17,  16,  15,  21,  28,  28,  21,   7,   1,  16,  15,  16,  14,
         52,  56,  53,  54,  53,  54,  31,  31,  38,  36,  36,  83,  88,
         31,  20,  21,  32,  35,  42,  75,  70,  64,  70, 151,  50,  43,
         34,  32,  37,  45,  40,  35,   8,  22,  58,  48,  23],
       [ 31,  24,  12,   9,  22,  27,  39,  12,  12,  27,  17,  23,  15,
         55,  44,  53,  55,  58,  50,  30,  16,  35,   4,  12,   7,   6,
     